version: '3'
services:
  web:
      container_name: node-mongo
      restart: always
      build: .
      ports:
        - "4000:3000"
      links:
        - mongo
      volumes:
        - .:/usr/src/app
      
  mongo:
      container_name: mongodb
      image: mongo
      ports:
        - "27018:27017"

